# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 21:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blocked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enroll', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enroll', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(default=b'images/default/no-img.jpg', upload_to=b'images/uploads')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enroll', models.CharField(max_length=12)),
                ('gender', models.CharField(max_length=6)),
                ('branch', models.CharField(max_length=20)),
                ('college', models.CharField(max_length=20)),
                ('blocked', models.ManyToManyField(blank=True, to='icebreaker_backend.Blocked')),
                ('contacts', models.ManyToManyField(blank=True, to='icebreaker_backend.Contacts')),
                ('picture', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='icebreaker_backend.Picture')),
            ],
        ),
    ]
