# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-20 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icebreaker_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pic_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
