# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-20 21:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icebreaker_backend', '0002_user_pic_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='icebreaker_backend.Picture'),
        ),
    ]
