# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-04 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icebreaker_backend', '0004_auto_20160920_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Random',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enroll', models.CharField(max_length=12)),
                ('gender', models.CharField(max_length=6)),
            ],
        ),
    ]
