# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-04 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icebreaker_backend', '0005_random'),
    ]

    operations = [
        migrations.AddField(
            model_name='random',
            name='time',
            field=models.IntegerField(default=123456789),
        ),
    ]
