# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-04 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icebreaker_backend', '0006_random_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='random',
            name='time',
            field=models.BigIntegerField(default=123456789),
        ),
    ]
