# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-12 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icebreaker_backend', '0007_auto_20161004_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(default=b'Hey there! I am using icebreaker.', max_length=200, null=True),
        ),
    ]
